language: ruby
rvm:
  - 2.2
before_install: gem install bundler -v 1.10.6
script: bundle exec rake test
notifications:
  slack:
    rooms:
      secure: w6pH+5mAAj89RpTD5wgpjTq3hoe2WGY2tmklr5MN176ixVaussdYA2LxBml39FyCuc2SigshyBO2fYeH+dg138jzNHpGc4fkfkV7+IUsn1+2XoGC5wkWXpboRJkZfKtmOpXsiopDr6zWBtO1oDsAtOFzOwzriy2g7qkRtP5z1UoVDyZQnEo/ZQ4mIR+yvQYJCDrAoV5McR4SXyZ0E2o56Ikn6y7F+r6+QRTLr2oMPag6dR6lNaxYYbbSd3j2KPKB0NOOHt6Od74tD57zLJVefd69lXM+Md5hUmyRzYvq9tUkKwmTtWfwMvLW4X3ZB3OceUVDYkU1gnMEy8FFGpxtMBgUgwDxnxBtAfyAPj06dxfIX79ifgZOpnUcukuVmY4bQKTZ3PuUD6EFbnnT/RrKsd2YWvb6cuB3SLxb4A+6KVwh7bnT3dQovbgDS4b/xDWsbjpDM1ob9BdChzIRIPhG6vhD5MrG0rz/nr4Mk1bFBXXbvtzyPi8pKG3jmVDlTok50jIvXm9ZsY76vISxZM1gev4ZehHhhlzQuJDkEyiEE4NGZBa2Z9q78y+uU13d+8X4FpDuLSBMJRsWQ30WL8rAgWVPexiLq60TM6stxIcil6+A8lOohPt6tncjbxBioW129Aplmy0QqsQzA0D3yC0IRwRYIL09Ixgod7gKhV3+kaQ=
