language: ruby
rvm:
  - 2.2
before_install: gem install bundler -v 1.10.6
script: bundle exec rake test
notifications:
  slack:
    rooms:
      secure: WqpcNDF/w8SS99aDT7Bwh1buhrylOqT+SqpOdxGjtG31dO/lB8s+K9ldAHaONN+l2Y4dzi3mZ3gSHMU7bzp0OjGvTH9tAZPpTA4Yzv7PjtHVPvLg4Es8pKsvbX+ooKkxJNycXYhi7v883ibBGmK9LfvseqASTr5MPM6qQsm6eGmMJMIMaHSU/Zu4MNLvCkGyFulKhEoVs4QigLVPpg164iai6/o4ckqYzCofssePX1RqntFDh8h6Dxn7KcnCi99Qgq8HTc8gPZYdbhEwWI5OsbB752yWRtqLYCLTanqjXPH0kuIqfnf5t6PvoSzSrZoCXwYiWtfhRDmV97w16iVhJhd5+RLpspk2MpAT1IIc4yRGO5YUL3gZUQ1H/mHkO2vzQf3s7bltcgv0GQA9lJzsFCSiO85Edhxyqg5agavpsdOIuiY9VyPnhLZrBxQeSuMkAMXSECKIY2ozbN0LfDU+B9ZC3r6u3Np/goxu3suQSUgveRnv9ubwt6ux2ujGtFpDEe8TEU732CQQ3GWiG4Npo0nxOHSt1ZZbfdwuxjE359mjmFcjp/shYfTjY5JsRh/flqCvIWOIvyKY/E6Zemk859T7BH1M6ujUQ+HXyXP3dO4Pd3n6xoHkH/9GRrH0d8MAbxK7RixIDr31umPWKiZdcDAWEUWDVIUCiCGVo+U41bc=
