language: ruby
rvm:
  - 2.2
  - 2.3
before_install: gem install bundler -v 1.10.6
script: bundle exec rake test
notifications:
  slack:
    rooms:
      secure: FRlBCvw60N0i2h6kTnzv2OFUM2m0KGQjf+wkHUusQ55orDa6YN4Pw1FjOVX1P/+KpYG5H/OgS+pYZo2c8aXOnC4Wn7+VRgZqUSs4lho04RsQrezmE8OuawUz7hc5wpT5sGN+O0yCn7P2ZEfwZdAawTtoNMPX1rzdTZqCK5Zygf7znbRdqQ7vZOqewoR1F3HV7VMYx0KeSGzcn/mjGYUNm4ofNYPGVmgkAX+5TyER538NEuitbrzafnIMBzS+/hs2dB2R1YQyXC7KHaxbmKd3O/YXeI40TTxtEKYQqWXpcx1/hl4zl9lV7169rnCA92LA7ttmFgcUEZcmsCOS9vqQeqfUYfQ4Ys/kNnzkTOTIvYSADM7ZrZjNrgGo7V8CjZKLUHLIW6mXAGtFbrPQED34EYRCjA8I7q9saDxCgZqamTNEI7MCOUtc7zXTm6oWStRcLzlwaCNrNoPcR3WfUfLsGgftkwOxpKDoT5x6STHfjPho+lBmZJNvjitac1IIbiTKVVQyJhE17nKpqbvomQIAakkjX18xsPpqontxCBEvRnh06f44UxMZRHKd+aPGin9EMMMjw+jOUiCMYmpXWI5n7jFDyul2P7o819A+5SgaVTbiSeE45Y4/p+HMOXwd3Ms/zbj6dlBgMd4fF8Dpy27nLhNvLg+sbT0cPqag1MTaXY8=
